# Generated by Django 5.2.10 on 2026-02-03 07:05

import django.db.models.deletion
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_front', models.ImageField(upload_to=kyc.models.kyc_upload_path)),
                ('aadhaar_back', models.ImageField(upload_to=kyc.models.kyc_upload_path)),
                ('pan', models.ImageField(upload_to=kyc.models.kyc_upload_path)),
                ('license', models.ImageField(upload_to=kyc.models.kyc_upload_path)),
                ('rc', models.ImageField(upload_to=kyc.models.kyc_upload_path)),
                ('selfie', models.ImageField(upload_to=kyc.models.kyc_upload_path)),
                ('bank_account', models.CharField(max_length=32)),
                ('ifsc', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='riders.rider')),
            ],
        ),
    ]
