# Generated by GitHub Copilot on 2026-02-04

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderkyc",
            name="aadhaar_front_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderkyc",
            name="aadhaar_back_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderkyc",
            name="pan_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderkyc",
            name="license_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderkyc",
            name="rc_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderkyc",
            name="selfie_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name="riderkyc",
            name="aadhaar_front",
        ),
        migrations.RemoveField(
            model_name="riderkyc",
            name="aadhaar_back",
        ),
        migrations.RemoveField(
            model_name="riderkyc",
            name="pan",
        ),
        migrations.RemoveField(
            model_name="riderkyc",
            name="license",
        ),
        migrations.RemoveField(
            model_name="riderkyc",
            name="rc",
        ),
        migrations.RemoveField(
            model_name="riderkyc",
            name="selfie",
        ),
    ]
